version: '3.1'

services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "5678:5678"
    environment:
      N8N_BASIC_AUTH_ACTIVE: "true"
      N8N_BASIC_AUTH_USER: "asserice"     # change this!
      N8N_BASIC_AUTH_PASSWORD: "AAaa1234$#"  # change this!
      WEBHOOK_TUNNEL_URL: "https://your-app.onrender.com"
    volumes:
      - n8n_data:/home/node/.n8n

volumes:
  n8n_data:
