services:
  - type: web
    name: n8n
    env: docker
    repo: https://github.com/AsserIsmail/AI-Automation-Shorts
    plan: free
    region: oregon
    dockerfilePath: ''
    dockerComposeFilePath: docker-compose.yml
    disk:
      name: n8n_data
      mountPath: /home/node/.n8n
      sizeGB: 1
